name: PHP CI

on:
  - push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: qwelp/php-project-lvl2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0.14'
      - name: Install
        run: make install
      - name: Run linter
        run: make lint
      - name: Run test
        run: make test
       - name: Run test & publish code coverage
       uses: qwelp/php-project-lvl2
       env:
         CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
       with:
         coverageCommand: make test-coverage
         coverageLocations: ${{github.workplace}}/build/logs/clover.xml:clover
         debug: true